
name: gpp_crm
description: Production-Ready GPP CRM for Printing Press Business.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  provider: ^6.1.1
  intl: ^0.19.0
  
  # UI & Fonts
  google_fonts: ^6.1.0
  timeline_tile: ^2.0.0
  fl_chart: ^0.66.0
  
  # Maps & Location
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  
  # Utils
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
